### ISSUE TITLE
Model and vocabulary files

### ISSUE THREAD

**Issue by hardik140397** [DeepLearnXMU/CAEncoder-NMT#1]
Can you please provide the link to model and vocabulary files.

**Comment by bzhangGo** [comment]
Hi, I didn't keep the well-trained models when I left XMU. So, I cannot give you more help. One option would be to train a model by yourself, using the CAEncoder here (theano-based), or [zero](https://github.com/bzhangGo/zero) (tensorflow-based).

**Comment by hardik140397** [comment]
Hi, no issues.
I am facing trouble finding vocabulary file. Can you provide some appropriate link from where I can download the required file.

**Comment by bzhangGo** [comment]
Hi, we have done two translation tasks in our paper: NIST Chinese-English task and WMT14 English-German task. Due to LDC policy, we have no right to distribute the NIST datasets. But for WMt14 dataset, you can download them from [stanford mt](https://nlp.stanford.edu/projects/nmt/), or [statmt website](http://statmt.org/wmt14/translation-task.html). 

For vocabulary construction, you can find more details [here](https://github.com/nyu-dl/dl4mt-tutorial/blob/master/data/build_dictionary.py).

**Comment by hardik140397** [comment]
ok thanks
